import { createThemeContract } from "@vanilla-extract/css";

/**
 * Material Design 3 Theme Contract
 * Defines the structure of theme tokens without values
 */
export const themeContract = createThemeContract({
  color: {
    primary: "",
    surfaceTint: "",
    onPrimary: "",
    primaryContainer: "",
    onPrimaryContainer: "",
    secondary: "",
    onSecondary: "",
    secondaryContainer: "",
    onSecondaryContainer: "",
    tertiary: "",
    onTertiary: "",
    tertiaryContainer: "",
    onTertiaryContainer: "",
    error: "",
    onError: "",
    errorContainer: "",
    onErrorContainer: "",
    background: "",
    onBackground: "",
    surface: "",
    onSurface: "",
    surfaceVariant: "",
    onSurfaceVariant: "",
    outline: "",
    outlineVariant: "",
    shadow: "",
    scrim: "",
    inverseSurface: "",
    inverseOnSurface: "",
    inversePrimary: "",
    primaryFixed: "",
    onPrimaryFixed: "",
    primaryFixedDim: "",
    onPrimaryFixedVariant: "",
    secondaryFixed: "",
    onSecondaryFixed: "",
    secondaryFixedDim: "",
    onSecondaryFixedVariant: "",
    tertiaryFixed: "",
    onTertiaryFixed: "",
    tertiaryFixedDim: "",
    onTertiaryFixedVariant: "",
    surfaceDim: "",
    surfaceBright: "",
    surfaceContainerLowest: "",
    surfaceContainerLow: "",
    surfaceContainer: "",
    surfaceContainerHigh: "",
    surfaceContainerHighest: "",
  },
  typography: {
    fontSize: {
      displayLarge: "",
      displayMedium: "",
      displaySmall: "",
      headlineLarge: "",
      headlineMedium: "",
      headlineSmall: "",
      titleLarge: "",
      titleMedium: "",
      titleSmall: "",
      bodyLarge: "",
      bodyMedium: "",
      bodySmall: "",
      labelLarge: "",
      labelMedium: "",
      labelSmall: "",
    },
    lineHeight: {
      displayLarge: "",
      displayMedium: "",
      displaySmall: "",
      headlineLarge: "",
      headlineMedium: "",
      headlineSmall: "",
      titleLarge: "",
      titleMedium: "",
      titleSmall: "",
      bodyLarge: "",
      bodyMedium: "",
      bodySmall: "",
      labelLarge: "",
      labelMedium: "",
      labelSmall: "",
    },
    fontWeight: {
      regular: "",
      medium: "",
      bold: "",
    },
    letterSpacing: {
      none: "",
      tight: "",
      normal: "",
      wide: "",
      wider: "",
      widest: "",
      extraWide: "",
    },
  },
  spacing: {
    0: "",
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    14: "",
    16: "",
    20: "",
    24: "",
    28: "",
    32: "",
  },
  elevation: {
    level0: "",
    level1: "",
    level2: "",
    level3: "",
    level4: "",
    level5: "",
  },
  shape: {
    none: "",
    extraSmall: "",
    small: "",
    medium: "",
    large: "",
    extraLarge: "",
    full: "",
  },
});
